services:
  nginx-image:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    container_name: nginx-app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/ubuntu/certs:/etc/nginx/certs

  chroma:
    image: chromadb/chroma
    container_name: chroma-app


  app-image:
    image: ${DOCKER_USERNAME}/vicki-app:latest
    container_name: vicki-app
    env_file:
      - .env
    volumes:
      - ./secret/github-app.pem:${GITHUB_KEY_FILE_PATH}:ro