-- 이 파일은 배포마다 재실행됩니다. 모든 문장은 반드시 멱등해야 합니다.
-- 파일명 앞의 숫자가 실행 순서입니다 (FK 때문에 순서가 중요).

-- GitHub이 발급한 user id를 그대로 PK로 사용합니다 (자동 증가 아님).
CREATE TABLE IF NOT EXISTS users (
    user_id    BIGINT PRIMARY KEY,
    login      TEXT   NOT NULL,
    avatar_url TEXT   NOT NULL
);

COMMENT ON COLUMN users.login IS 'Github user login name';
COMMENT ON COLUMN users.avatar_url IS 'Github user profile url';

-- GitHub이 발급한 repository id를 그대로 PK로 사용합니다 (자동 증가 아님).
CREATE TABLE IF NOT EXISTS repositories (
    repo_id         BIGINT PRIMARY KEY,
    installation_id BIGINT NOT NULL,
    full_name       TEXT   NOT NULL
);

-- convention_id는 우리가 발급하므로 IDENTITY입니다.
CREATE TABLE IF NOT EXISTS conventions (
    convention_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_id       BIGINT NOT NULL REFERENCES repositories (repo_id),
    filename      TEXT   NOT NULL,
    filecontent   TEXT   NOT NULL,
    filehash      BYTEA  NOT NULL,
    uploaded_by   BIGINT NOT NULL REFERENCES users (user_id),
    CONSTRAINT unique_repo_filehash UNIQUE (repo_id, filehash)
);

CREATE TABLE IF NOT EXISTS sessions (
    session_id    UUID        PRIMARY KEY,
    user_id       BIGINT      NOT NULL REFERENCES users (user_id),
    access_token  TEXT        NOT NULL,
    refresh_token TEXT        NOT NULL,
    expires_at    TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_conventions_repo_id ON conventions (repo_id);
CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions (user_id);
